/hik_camera_ros2_driver:
  ros__parameters:
    camera_info_url: "package://hik_camera_ros2_driver/config/camera_info.yaml"
    adc_bit_depth: "Bits_8"         # If using "BayerRG8", <adc_bit_depth> must be set as "Bits_8"; otherwise, it can be "Bits_8" or "Bits_12"
    use_sensor_data_qos: false
    camera_name: "camera"
    # frame_id: "optical_frame"     # If not set, it will be set as <camera_name>_optical_frame
    # camera_topic: "image"         # If not set, it will be set as <camera_name>/image

    acquisition_frame_rate: 144.0   # Unit: Hz
    exposure_time: 2500             # Unit: us
    gain: 12.0                      # Range: 0.0 ~ 16.9, Unit: dB
