red_standard_robot1:
  serial_driver:
    ros__parameters:
      urdf_type: "sentry"
      timestamp_offset: 0.006
      device_name: /dev/ttyACM0
      baud_rate: 115200
      flow_control: none
      parity: none
      stop_bits: "1"